# config for centnet-voip-sniffer
# created by Wayne Yao, 2020-11-17

[logging]
    logPath = "./log"
    logFile = "main.log"
    fileLevel= "DEBUG"
    consoleLevel = "DEBUG"
    maxAge = 7
    maxSize =  10

[fileParser]
    rootPath = "/"
    startDatePath = "202012/20201201"
    maxParseProcs = 32

[kafka]
    # 诈骗模型服务
    [kafka.fraudModelProducer]
        enable = false
        topic = "CDR"
        broker = "192.168.1.225:9092"
        frequency = 500
        maxMessage = 100000

[sniffer]
    Device = "enp2s0"
    SnapLen = 65535
    Filter = "udp"

[mysql]
    dsn = "centnet_cdrrs:123456@tcp(192.168.1.205:3306)/centnet_cdrrs?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    # 话单缓存刷新间隔，单位：秒
    flushPeriod = 10
    # 话单批量插入条数
    maxFlushCapacity = 5000
    # 话单缓存最大数量
    maxCacheCapacity = 20000

[redis]
    host = "192.168.1.205:6379"
    password = ""
    idleTimeout = 600
    maxIdle = 10
    maxActive = 10000
    # 缓存失效时间默认为30m
    cacheExpire = 1800