# config for centnet-voip-sniffer
# created by Wayne Yao, 2020-11-17

[logging]
    logPath = "./log"
    logFile = "main.log"
    fileLevel= "DEBUG"
    consoleLevel = "DEBUG"
    maxAge = 7
    maxSize =  10

[fileParser]
    rootPath = "/"
    startDatePath = "202012/20201201"
    maxParseProcs = 200

[kafka]
    # sip原始消息生产者
    [kafka.sipPacketProducer]
        topic = "RawVoipPacket"
        broker = "192.168.1.205:9092"
        frequency = 500
        maxMessage = 1000000

    # sip消息分析消费者
    [kafka.sipPacketConsumer]
        topic = "RawVoipPacket"
        broker = "192.168.1.205:9092"
        group = "VoipAnalyticGroup"
        groupMembers = 1
        # 统计流速时间间隔
        flowRateFlushPeriod = 3

    # 待还原话单数据生产者
    [kafka.restoreCDRProducer]
        topic = "SemiFinishedCDR"
        broker = "192.168.1.205:9092"
        frequency = 500
        maxMessage = 1000000

    # 话单数据生产者
    [kafka.restoreCDRConsumer]
        topic = "SemiFinishedCDR"
        broker = "192.168.1.205:9092"
        group = "CDRRestoreGroup"
        groupMembers = 1
        # 统计流速时间间隔
        flowRateFlushPeriod = 3

    # 诈骗模型服务
    [kafka.fraudModelProducer]
        topic = "CDR"
        broker = "192.168.1.225:9092"
        frequency = 500
        maxMessage = 1000000

[sniffer]
    Device = "enp2s0"
    SnapLen = 65535
    Filter = "udp"

[mysql]
    dsn = "root:123456@tcp(192.168.1.205:3306)/centnet_cdrrs?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    # 话单缓存刷新间隔，单位：秒
    flushPeriod = 10
    # 话单批量插入条数
    maxFlushCapacity = 5000
    # 话单缓存最大数量
    maxCacheCapacity = 20000

[redis]
    host = "192.168.1.205:6379"
    password = ""
    idleTimeout = 600
    maxIdle = 10
    maxActive = 10000
    # 缓存失效时间默认为30m
    cacheExpire = 1800