# config for centnet-voip-sniffer
# created by Wayne Yao, 2020-11-17

[logging]
    logPath = "./log"
    logFile = "main.log"
    fileLevel= "DEBUG"
    consoleLevel = "DEBUG"
    maxAge = 7
    maxSize =  10

[kafka]
    # sip原始消息生产者
    [kafka.sipPacketProducer]
        topic = "SipPacket"
        broker = "192.168.1.205:9092"
        frequency = 500
        maxMessage = 1000000

    # sip消息分析消费者
    [kafka.sipPacketConsumer]
        topic = "SipPacket"
        broker = "192.168.1.205:9092"
        partition = 4
        replication = 1
        group = "AnalyticCluster"
        version = "2.0.0"
        numRoutine = 1

    # 待还原话单数据生产者
    [kafka.restoreCDRProducer]
        topic = "restoreCDRData"
        broker = "192.168.1.205:9092"
        frequency = 500
        maxMessage = 1000000

    # 话单数据生产者
    [kafka.restoreCDRConsumer]
        topic = "restoreCDRData"
        broker = "192.168.1.205:9092"
        partition = 4
        replication = 1
        group = "RestoreCDRCluster"
        version = "2.0.0"
        numRoutine = 4

    # 诈骗模型服务
    [kafka.fraudModelProducer]
        topic = "CDR"
        broker = "192.168.1.225:9092"
        frequency = 500
        maxMessage = 1000000

[sniffer]
    Device = "enp2s0"
    SnapLen = 65535
    Filter = "udp"

[mysql]
    dsn = "root:123456@tcp(192.168.1.205:3306)/centnet_voip?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    flushPeriod = 10
    maxFlushCapacity = 5000
    maxCacheCapacity = 10000

[redis]
    host = "192.168.1.205:6379"
    password = ""
    idleTimeout = 600
    maxIdle = 10
    maxActive = 10000
    cacheExpire = 3600