# config for centnet-cdrrs
# created by Wayne Yao, 2020-11-17

# 日志相关配置
[logging]

    logPath = "./log"
    logFile = "main.log"
    fileLevel= "DEBUG"
    consoleLevel = "DEBUG"
    maxAge = 7
    maxSize =  10

# 解析原始数据文件配置
[fileParser]
	# 以过滤规则ID命名的绝对路径
    rootPath = "/home"
    # 开始解析哪天目录下的文件
    startDatePath = "202012/20201201"
    # 最大并发解析线程数(设置0为系统默认值)
    maxParseProcs = 0

# 话单数据库配置
[orm]
	# 连接地址，格式为user:password@tcp(host:port)/db_name?paramters...
    dsn = "centnet_cdrrs:123456@tcp(192.168.1.205:3306)/centnet_cdrrs?timeout=10s&readTimeout=10s&writeTimeout=10s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 10
    idle = 100
    idleTimeout = "10m"

[redis]
    active = 100
    idle = 5
    idleTimeout = "1m"
    waitTimeout = "0s"
    wait = false

    # redis name, for trace
    Name = "redis"
    Proto = "tcp"
    Addr = "192.168.1.205:6379"
    Auth = ""
    DialTimeout = "3s"
    ReadTimeout = "3s"
    WriteTimeout = "3s"

[cdr]
    # 临时数据缓存时间
    cachedLife = "1h"
    # 话单批量插入条数
    maxFlushCap = 10000
    # 话单缓存最大数量
    maxCacheCap = 100000
    # 话单缓存刷新间隔
    cdrFlushPeriod = "5s"
    # 话单分表间隔时间
    cdrTablePeriod = "5m"

[kafka]
    # 诈骗模型服务
    [kafka.fraudModel]
    	# 默认关闭，不推送数据，诈骗模型部署后可打开
        enable = false
        topic = "CDR"
        broker = "192.168.1.225:9092"
        frequency = "500ms"
        maxMessage = 100000