# config for centnet-cdrrs
# created by Wayne Yao, 2020-11-17

# 日志相关配置
[logging]

    logPath = "./log"
    logFile = "main.log"
    fileLevel= "DEBUG"
    consoleLevel = "DEBUG"
    maxAge = 7
    maxSize =  10

# 解析原始数据文件配置
[fileParser]
	# 以过滤规则ID命名的绝对路径
    rootPath = "/"									#
    # 开始解析哪天目录下的文件
    startDatePath = "202012/20201201"
    # 最大并发解析线程数
    maxParseProcs = 32

# 话单数据库配置
[mysql]
	# 连接地址，格式为user:password@tcp(host:port)/db_name?paramters...
    dsn = "centnet_cdrrs:123456@tcp(192.168.1.205:3306)/centnet_cdrrs?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    # 话单缓存刷新间隔，单位：秒
    flushPeriod = 10
    # 话单批量插入条数
    maxFlushCapacity = 5000
    # 话单缓存最大数量
    maxCacheCapacity = 20000

# 缓存服务配置
[redis]
	# 主机地址
    host = "192.168.1.205:6379"
    # 为空，不填
    password = ""
    idleTimeout = 600
    maxIdle = 10
    maxActive = 10000
    # 缓存失效时间默认为1h
    cacheExpire = 3600

[kafka]
    # 诈骗模型服务
    [kafka.fraudModelProducer]
    	# 默认关闭不推送，诈骗模型部署后可打开
        enable = false
        topic = "CDR"
        broker = "192.168.1.225:9092"
        frequency = 500
        maxMessage = 100000